/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lh.quickstart;

import java.io.IOException;

import io.littlehorse.sdk.common.config.LHConfig;
import io.littlehorse.sdk.worker.LHTaskWorker;

public class App {

    private static void registerTaskWorker(LHConfig config) throws IOException {
        LHTaskWorker worker = new LHTaskWorker(new Greeter(), "greet", config);
        worker.registerTaskDef(true);
    }

    public static void main(String[] args) throws IOException {
        LHConfig config = new LHConfig();
        registerTaskWorker(config);
        System.out.println("Done!");
    }
}
