/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lh.quickstart;

import java.io.IOException;

import io.littlehorse.sdk.common.config.LHConfig;
import io.littlehorse.sdk.worker.LHTaskWorker;

public class App {

    private static void registerWorkflow() throws IOException {
        LHConfig config = new LHConfig();

        LHTaskWorker worker = new LHTaskWorker(new Greeter(), "greet", config);
        worker.registerTaskDef(true);

        QuickstartWorkflow quickstart = new QuickstartWorkflow();
        quickstart.getWorkflow().registerWfSpec(config.getBlockingStub());


    }
    private static void registerAndStartWorker(LHConfig config) throws IOException {
        LHTaskWorker worker = new LHTaskWorker(new Greeter(), "greet", config);
        worker.registerTaskDef(true);

        System.out.println("Done registering task definition, now starting worker");
        Runtime.getRuntime().addShutdownHook(new Thread(worker::close));

        worker.start();
    }

    public static void main(String[] args) throws IOException {

        if (args.length !=1 || (!args[0].equals("register") && !args[0].equals("worker"))){
            System.err.println("Please provide one argument: either 'register' or 'worker' ");
            System.exit(1);
        }

        if(args[0].equals("register")){
            registerWorkflow();
        } else{
            LHConfig config = new LHConfig();
            registerAndStartWorker(config);
            System.out.println("Done starting the worker!");
        }


    }
}
